### ISSUE TITLE
downgrade cmake_minimum_required to 3.5

### ISSUE THREAD

**Issue by p5-vbnekit** [Vezhenkov/Task1#4]
Судя по коду нет необходимости требовать от `cmake` быть настолько свежей.
Просьба исправить на `cmake_minimum_required(VERSION 3.5)`.

**Comment by Vezhenkov** [comment]
Исправил
[CMake: cmake_minimum_required downgraded to 3.5](https://github.com/Vezhenkov/Task1/commit/841e86a32daf5970028610780a13eaeac7b6c0ae)
